//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace booking.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("booking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivna tura.
        /// </summary>
        internal static string Active_tour {
            get {
                return ResourceManager.GetString("Active_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj sliku.
        /// </summary>
        internal static string Add_photo {
            get {
                return ResourceManager.GetString("Add_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj slike(opciono):.
        /// </summary>
        internal static string Add_photo_optional {
            get {
                return ResourceManager.GetString("Add_photo_optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodati prosti zahtevi.
        /// </summary>
        internal static string Added_simple_requests {
            get {
                return ResourceManager.GetString("Added_simple_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatni komentar:.
        /// </summary>
        internal static string Additional_comment {
            get {
                return ResourceManager.GetString("Additional_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatne informacije.
        /// </summary>
        internal static string Additional_information {
            get {
                return ResourceManager.GetString("Additional_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tura je odobreno od strane vodiča.
        /// </summary>
        internal static string approved_mess {
            get {
                return ResourceManager.GetString("approved_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slobodnih mesta.
        /// </summary>
        internal static string Available_space {
            get {
                return ResourceManager.GetString("Available_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupni vaučeri.
        /// </summary>
        internal static string Available_vouchers {
            get {
                return ResourceManager.GetString("Available_vouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosecan br. godina.
        /// </summary>
        internal static string Avg_guest_age {
            get {
                return ResourceManager.GetString("Avg_guest_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to je prosečan broj ljudi na zahtevima.
        /// </summary>
        internal static string avg_ppl_mess {
            get {
                return ResourceManager.GetString("avg_ppl_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bukiraj turu.
        /// </summary>
        internal static string Book_a_tour {
            get {
                return ResourceManager.GetString("Book_a_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bukiraj turu.
        /// </summary>
        internal static string Book_a_tour_header {
            get {
                return ResourceManager.GetString("Book_a_tour_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        internal static string Change_lang {
            get {
                return ResourceManager.GetString("Change_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promena teme.
        /// </summary>
        internal static string Change_theme {
            get {
                return ResourceManager.GetString("Change_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi godinu.
        /// </summary>
        internal static string Choose_year {
            get {
                return ResourceManager.GetString("Choose_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Očisti.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završene ture.
        /// </summary>
        internal static string Completed_tours {
            get {
                return ResourceManager.GetString("Completed_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompleksni zahtevi.
        /// </summary>
        internal static string Complex_requests {
            get {
                return ResourceManager.GetString("Complex_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna znamenitost:.
        /// </summary>
        internal static string Current_checkpoint {
            get {
                return ResourceManager.GetString("Current_checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje(h).
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum završetka.
        /// </summary>
        internal static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme završetka.
        /// </summary>
        internal static string end_time {
            get {
                return ResourceManager.GetString("end_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi ime kompleksnog zahteva.
        /// </summary>
        internal static string Enter_complex_request_name {
            get {
                return ResourceManager.GetString("Enter_complex_request_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum isteka.
        /// </summary>
        internal static string expiry_date {
            get {
                return ResourceManager.GetString("expiry_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodni kompleksni zahtevi.
        /// </summary>
        internal static string Former_complex_requests {
            get {
                return ResourceManager.GetString("Former_complex_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodni zahtevi.
        /// </summary>
        internal static string Former_simple_requests {
            get {
                return ResourceManager.GetString("Former_simple_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        internal static string From_message {
            get {
                return ResourceManager.GetString("From_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generiši.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id vodiča.
        /// </summary>
        internal static string guideId {
            get {
                return ResourceManager.GetString("guideId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli.
        /// </summary>
        internal static string Header_welcome {
            get {
                return ResourceManager.GetString("Header_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priključi se .
        /// </summary>
        internal static string Join_tour {
            get {
                return ResourceManager.GetString("Join_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznavanje jezika:.
        /// </summary>
        internal static string Lang_knowledge {
            get {
                return ResourceManager.GetString("Lang_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz zahteva tura po jezicima.
        /// </summary>
        internal static string Language_chart {
            get {
                return ResourceManager.GetString("Language_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz zahteva tura po lokacijama.
        /// </summary>
        internal static string Location_chart {
            get {
                return ResourceManager.GetString("Location_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalni br. ljudi.
        /// </summary>
        internal static string max_guest_count {
            get {
                return ResourceManager.GetString("max_guest_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatni detalji.
        /// </summary>
        internal static string more_details {
            get {
                return ResourceManager.GetString("more_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje ture.
        /// </summary>
        internal static string My_tours {
            get {
                return ResourceManager.GetString("My_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obaveštenja.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj gostiju.
        /// </summary>
        internal static string Number_of_guests {
            get {
                return ResourceManager.GetString("Number_of_guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum dobijanja.
        /// </summary>
        internal static string obtain_date {
            get {
                return ResourceManager.GetString("obtain_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj ljudi.
        /// </summary>
        internal static string people_count {
            get {
                return ResourceManager.GetString("people_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceni vodiča.
        /// </summary>
        internal static string Rate_guide {
            get {
                return ResourceManager.GetString("Rate_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skoro odobrene ture.
        /// </summary>
        internal static string Recently_approved_tours {
            get {
                return ResourceManager.GetString("Recently_approved_tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tura je odbijeno.
        /// </summary>
        internal static string rejected_mess {
            get {
                return ResourceManager.GetString("rejected_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generiši izveštaj o posećenim turama.
        /// </summary>
        internal static string Report_message {
            get {
                return ResourceManager.GetString("Report_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatraži.
        /// </summary>
        internal static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevi.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogledaj više.
        /// </summary>
        internal static string see_more {
            get {
                return ResourceManager.GetString("see_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi vaučer.
        /// </summary>
        internal static string Select_voucher {
            get {
                return ResourceManager.GetString("Select_voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosti zahtev.
        /// </summary>
        internal static string Simple_request {
            get {
                return ResourceManager.GetString("Simple_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosti zahtevi.
        /// </summary>
        internal static string Simple_requests {
            get {
                return ResourceManager.GetString("Simple_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum početka.
        /// </summary>
        internal static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme početka.
        /// </summary>
        internal static string start_time {
            get {
                return ResourceManager.GetString("start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihvati.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okvirno vreme.
        /// </summary>
        internal static string Time_estimation {
            get {
                return ResourceManager.GetString("Time_estimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string To_message {
            get {
                return ResourceManager.GetString("To_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zanimljivost ture:.
        /// </summary>
        internal static string Tour_enjoyment {
            get {
                return ResourceManager.GetString("Tour_enjoyment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznavanje ture:.
        /// </summary>
        internal static string Tour_knowledge {
            get {
                return ResourceManager.GetString("Tour_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id ture.
        /// </summary>
        internal static string tourId {
            get {
                return ResourceManager.GetString("tourId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestije tura.
        /// </summary>
        internal static string Tours_you_might_like {
            get {
                return ResourceManager.GetString("Tours_you_might_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaučeri.
        /// </summary>
        internal static string Vouchers {
            get {
                return ResourceManager.GetString("Vouchers", resourceCulture);
            }
        }
    }
}
